/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ConfirmPasswordReset200Response
 */
export interface ConfirmPasswordReset200Response {
  /**
   *
   * @type {string}
   * @memberof ConfirmPasswordReset200Response
   */
  message?: string;
}

/**
 * Check if a given object implements the ConfirmPasswordReset200Response interface.
 */
export function instanceOfConfirmPasswordReset200Response(value: object): value is ConfirmPasswordReset200Response {
  return true;
}

export function ConfirmPasswordReset200ResponseFromJSON(json: any): ConfirmPasswordReset200Response {
  return ConfirmPasswordReset200ResponseFromJSONTyped(json, false);
}

export function ConfirmPasswordReset200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmPasswordReset200Response {
  if (json == null) {
    return json;
  }
  return {
    message: json["message"] == null ? undefined : json["message"],
  };
}

export function ConfirmPasswordReset200ResponseToJSON(json: any): ConfirmPasswordReset200Response {
  return ConfirmPasswordReset200ResponseToJSONTyped(json, false);
}

export function ConfirmPasswordReset200ResponseToJSONTyped(value?: ConfirmPasswordReset200Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    message: value["message"],
  };
}
