/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ResetPasswordResponse
 */
export interface ResetPasswordResponse {
  /**
   *
   * @type {string}
   * @memberof ResetPasswordResponse
   */
  token?: string;
  /**
   *
   * @type {Date}
   * @memberof ResetPasswordResponse
   */
  expiresAt?: Date;
}

/**
 * Check if a given object implements the ResetPasswordResponse interface.
 */
export function instanceOfResetPasswordResponse(value: object): value is ResetPasswordResponse {
  return true;
}

export function ResetPasswordResponseFromJSON(json: any): ResetPasswordResponse {
  return ResetPasswordResponseFromJSONTyped(json, false);
}

export function ResetPasswordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPasswordResponse {
  if (json == null) {
    return json;
  }
  return {
    token: json["token"] == null ? undefined : json["token"],
    expiresAt: json["expiresAt"] == null ? undefined : new Date(json["expiresAt"]),
  };
}

export function ResetPasswordResponseToJSON(json: any): ResetPasswordResponse {
  return ResetPasswordResponseToJSONTyped(json, false);
}

export function ResetPasswordResponseToJSONTyped(value?: ResetPasswordResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    token: value["token"],
    expiresAt: value["expiresAt"] == null ? value["expiresAt"] : value["expiresAt"].toISOString(),
  };
}
