/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ResetPasswordConfirm
 */
export interface ResetPasswordConfirm {
  /**
   *
   * @type {string}
   * @memberof ResetPasswordConfirm
   */
  token?: string;
  /**
   *
   * @type {string}
   * @memberof ResetPasswordConfirm
   */
  password?: string;
}

/**
 * Check if a given object implements the ResetPasswordConfirm interface.
 */
export function instanceOfResetPasswordConfirm(value: object): value is ResetPasswordConfirm {
  return true;
}

export function ResetPasswordConfirmFromJSON(json: any): ResetPasswordConfirm {
  return ResetPasswordConfirmFromJSONTyped(json, false);
}

export function ResetPasswordConfirmFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPasswordConfirm {
  if (json == null) {
    return json;
  }
  return {
    token: json["token"] == null ? undefined : json["token"],
    password: json["password"] == null ? undefined : json["password"],
  };
}

export function ResetPasswordConfirmToJSON(json: any): ResetPasswordConfirm {
  return ResetPasswordConfirmToJSONTyped(json, false);
}

export function ResetPasswordConfirmToJSONTyped(value?: ResetPasswordConfirm | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    token: value["token"],
    password: value["password"],
  };
}
